<?php

include 'assets/codes/config.php';

?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>
            Curved Arrow Networks
        </title>

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="assets/css/style.css">
        <link rel="stylesheet" href="assets/css/bootstrap.min.css">
        <link rel="stylesheet" href="assets/icons/bootstrap-icons.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
        
        
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
        <script href="assets/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script href="assets/js/bootstrap.min.js" crossorigin="anonymous"></script>
    </head>
    
    <body>
      


        <section id="brand">
          <div class="container-fluid">
            <center>
              
              <h3 class="text-danger">Curved Arrow Networks, LLC</h3>
              <img class="navbar-brand" src="assets/logos/bird.svg" alt="logo"  height="80vh" />
              <a href="assets/codes/controller.php?logout=true"><button class="btn btn-large btn-dark">Logout</button></a>
              

              <div class="container-fluid">
                <div class="row">
                  <div class="col col-lg-4">
                    <form action="assets/codes/controller.php" method="post">

                      <div class="mb-3">
                        <select name="updateId">
                          <option value="2">Valarie</option>
                          <option value="1">David</option>
                        </select>
                      </div>

                      <div class="mb-3">
                        <label for="password" class="form-label"><strong>New Password</strong></label>
                          <input type="password" class="form-control " name="password" />

                        <button class="btn btn-primary" name="changePW__btn">Change Password</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>

            </center>
          </div>
        </section>      

        <section class="newClients">
          <div class="container-fluid">
            <?php
              include 'assets/codes/staff/tables/newClients.php';
            ?>
          </div>
        </section>

  <br /><br /><br />
  
        <section class="existingClients">
          <div class="container-fluid">
            <?php
              include 'assets/codes/staff/tables/existingClients.php';
            ?>
          </div>
        </section>
      <br />
      <!-- <script src="assets/scripts.js"></script> -->
  </body>
  <script src="assets/js/scripts.js"></script>
</html>